# Generated by Django 5.0.1 on 2024-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
