# Generated by Django 5.0.1 on 2024-01-24 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('dias', models.IntegerField()),
                ('profesional', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
