# Generated by Django 5.0.1 on 2024-01-22 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('alarma', models.BooleanField(default=False)),
                ('mensualidad', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='vencimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
