# Generated by Django 5.0.1 on 2024-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vencimiento',
            name='mensualidad',
            field=models.BooleanField(default=False),
        ),
    ]
