# Generated by Django 5.0.1 on 2024-01-31 00:51

import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_categoria_documentopdf_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopdf',
            name='archivo',
            field=models.FileField(upload_to='documentos_pdf/', validators=[documentos.models.validate_pdf]),
        ),
    ]
