# Generated by Django 5.0.1 on 2024-01-31 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documentopdf_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopdf',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
